### ISSUE TITLE
Buttons stored by ButtonManager are not deleted once connection disconnects

### ISSUE THREAD

**Issue by LFSPovo** [Dygear/PRISM#28]
I found out that the buttons stored by the ButtonManager aren't deleted from the $buttons array in prism_buttonmanager.php. This means that if a user connects, buttons are displayed, user disconnects and then reconnects again, buttons aren't shown anymore.

Solution to this is that a plugin developer must manually delete all buttons in the IS_CNL packet event.

It would be nice if it could be done automatically by PRISM! :)

**Comment by T3charmy** [comment]
I'll try and see if I can come up with a solution for this while I'm working on PRISM this weekend.

**Comment by T3charmy** [comment]
This issue has been fixed in my local copy.
