### ISSUE TITLE
MST/MTC/MSX colour breaks

### ISSUE THREAD

**Issue by Krammeh** [Dygear/PRISM#4]
After sending long messages, the colour breaks and reverts to default.

**Comment by T3charmy** [comment]
I'm looking at finally fixing this. I have an idea in mind that makes use of strrchr

**Comment by T3charmy** [comment]
Issues are now resolved as of 0.5.0.2

**Comment by T3charmy** [comment]
@LFSPovo Your issue is still pending a good way to do that. I suppose I could check if the string starts with / take upto the first space and prepend that to every message. I will look at best options when I have free time on Wednesday.
