### ISSUE TITLE
Translation Engine: Optimize Translation loading

### ISSUE THREAD

**Issue by T3charmy** [Dygear/PRISM#64]
@Dave-LB brought a good point to my attention.

When a translation file is loaded for the first time, it should be loaded into memory so that we are able to optimize hard disk read/write operations and translation performance.

**Comment by Dygear** [comment]
I'm surprised it's not. Just make sure there is a "reload" command for the translation files, so it doesn't require a restart should they update some of their settings.

**Comment by T3charmy** [comment]
@Dygear Yea, when i coded it I didn't think about it at the time, just wanted something that worked. I'll see what the best way to implement the reload command for it as well.

**Comment by T3charmy** [comment]
@Dave-LB I think I'm going to convert the translation system into a plugin of sorts. I will work on this after work tomorrow and do some testing. I might have to actually change the way translations are handled completely. but we'll see how it works with the new system. I have a few concerns that may cause issues.

**Comment by T3charmy** [comment]
This has been fixed in PRISM v0.6.0 ( #66 )
